### ISSUE TITLE
type=one-liner `Cannot read property 'template' of undefined`

### ISSUE THREAD

**Issue by Ragemalik** [startmc/startmc.sh#22]
I am unable to use the one liner type the error i get is Cannot read property 'template' of undefined

**Comment by tadhgboyle** [comment]
Cannot reproduce... are you doing anything different?
<img width="1725" alt="Screen Shot 2021-12-26 at 1 08 47 PM" src="https://user-images.githubusercontent.com/26070412/147420158-b00c7e16-7bd7-4cd4-ac8c-3575ce59dcdd.png">
